/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DirectionLedgerRouteImport } from './routes/direction-ledger'
import { Route as DirectionScoreboardRouteImport } from './routes/direction-scoreboard'
import { Route as DirectionScoreboardOptionsRouteImport } from './routes/direction-scoreboard-options'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionLedgerRoute = DirectionLedgerRouteImport.update({
  id: '/direction-ledger',
  path: '/direction-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionScoreboardRoute = DirectionScoreboardRouteImport.update({
  id: '/direction-scoreboard',
  path: '/direction-scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionScoreboardOptionsRoute =
  DirectionScoreboardOptionsRouteImport.update({
    id: '/direction-scoreboard-options',
    path: '/direction-scoreboard-options',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/direction-ledger': typeof DirectionLedgerRoute
  '/direction-scoreboard': typeof DirectionScoreboardRoute
  '/direction-scoreboard-options': typeof DirectionScoreboardOptionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/direction-ledger': typeof DirectionLedgerRoute
  '/direction-scoreboard': typeof DirectionScoreboardRoute
  '/direction-scoreboard-options': typeof DirectionScoreboardOptionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/direction-ledger': typeof DirectionLedgerRoute
  '/direction-scoreboard': typeof DirectionScoreboardRoute
  '/direction-scoreboard-options': typeof DirectionScoreboardOptionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/direction-ledger'
    | '/direction-scoreboard'
    | '/direction-scoreboard-options'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/direction-ledger'
    | '/direction-scoreboard'
    | '/direction-scoreboard-options'
  id:
    | '__root__'
    | '/'
    | '/direction-ledger'
    | '/direction-scoreboard'
    | '/direction-scoreboard-options'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectionLedgerRoute: typeof DirectionLedgerRoute
  DirectionScoreboardRoute: typeof DirectionScoreboardRoute
  DirectionScoreboardOptionsRoute: typeof DirectionScoreboardOptionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direction-ledger': {
      id: '/direction-ledger'
      path: '/direction-ledger'
      fullPath: '/direction-ledger'
      preLoaderRoute: typeof DirectionLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direction-scoreboard': {
      id: '/direction-scoreboard'
      path: '/direction-scoreboard'
      fullPath: '/direction-scoreboard'
      preLoaderRoute: typeof DirectionScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direction-scoreboard-options': {
      id: '/direction-scoreboard-options'
      path: '/direction-scoreboard-options'
      fullPath: '/direction-scoreboard-options'
      preLoaderRoute: typeof DirectionScoreboardOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectionLedgerRoute: DirectionLedgerRoute,
  DirectionScoreboardRoute: DirectionScoreboardRoute,
  DirectionScoreboardOptionsRoute: DirectionScoreboardOptionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
